trigger:
- QA/infra
variables:
  azureSubscription: 'POC_DEVMIG_SP'
  region: 'southcentralus'
  environment: 'qa'
  project: 'pocrandd01'
pool:
  vmImage: 'windows-latest'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: $(azureSubscription)
    scriptType: 'ps'
    scriptLocation: 'scriptPath'
    scriptPath: 'infra/infrapocrandd.ps1'
    arguments: '$(environment) $(project) $(region)'
